/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comment/': RouteRecordInfo<
      '/comment/',
      '/comment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/': RouteRecordInfo<
      '/gallery/',
      '/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/demo/': RouteRecordInfo<
      '/gallery/demo/',
      '/gallery/demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/README': RouteRecordInfo<
      '/gallery/README',
      '/gallery/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navigation/': RouteRecordInfo<
      '/navigation/',
      '/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/ai-workflow': RouteRecordInfo<
      '/posts/ai-workflow',
      '/posts/ai-workflow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/code-less-architect-more': RouteRecordInfo<
      '/posts/code-less-architect-more',
      '/posts/code-less-architect-more',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/digital-garden-notes': RouteRecordInfo<
      '/posts/digital-garden-notes',
      '/posts/digital-garden-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mascot-intro': RouteRecordInfo<
      '/posts/mascot-intro',
      '/posts/mascot-intro',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__0c96bd38ce79d09258d15692ed4bcd78/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parse_8fdf29cdad2c1236c6e9a880f31254c6/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/comment/index.md': {
      routes:
        | '/comment/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/index.md': {
      routes:
        | '/gallery/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/demo/index.md': {
      routes:
        | '/gallery/demo/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/README.md': {
      routes:
        | '/gallery/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/navigation/index.md': {
      routes:
        | '/navigation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__0c96bd38ce79d09258d15692ed4bcd78/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/posts/ai-workflow.md': {
      routes:
        | '/posts/ai-workflow'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/code-less-architect-more.md': {
      routes:
        | '/posts/code-less-architect-more'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/digital-garden-notes.md': {
      routes:
        | '/posts/digital-garden-notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mascot-intro.md': {
      routes:
        | '/posts/mascot-intro'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/search/index.md': {
      routes:
        | '/search/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
